### ISSUE TITLE
Banco de Images

### ISSUE THREAD

**Issue by J-S-Oliveira** [Dinamica-dos-Fluidos-CFD/Jonas_Santos_170050653#1]
![numero de pontos](https://user-images.githubusercontent.com/70406366/95993724-d5d40780-0e05-11eb-9a12-c1b9fbad3d23.PNG)
![paredes](https://user-images.githubusercontent.com/70406366/95994079-37947180-0e06-11eb-9745-2cf033d7fd64.png)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96003443-9bbc3300-0e10-11eb-8ee8-c42309d47ae3.png)

**Comment by J-S-Oliveira** [comment]
![segmentação da malha](https://user-images.githubusercontent.com/70406366/96011696-a0391980-0e19-11eb-9e94-f773d0c8eaa4.PNG)

**Comment by J-S-Oliveira** [comment]
![Uploading geometria.png…]()

**Comment by J-S-Oliveira** [comment]
![geometria](https://user-images.githubusercontent.com/70406366/96736287-d71bac00-1392-11eb-9b26-1cd477ba4365.png)

**Comment by UnB-EngAero-170050653** [comment]
![image](https://user-images.githubusercontent.com/70406366/96738208-dedc5000-1394-11eb-803b-4e647f700351.png)

**Comment by J-S-Oliveira** [comment]
![CodeCogsEqn](https://user-images.githubusercontent.com/70406366/96739589-53fc5500-1396-11eb-99d6-962d58b81128.gif)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96740463-3da2c900-1397-11eb-8ec6-671f10f38ecd.png)

**Comment by UnB-EngAero-170050653** [comment]
![Uploading WhatsApp Image 2020-10-15 at 20.01.33.jpeg…]()

**Comment by UnB-EngAero-170050653** [comment]
![Uploading WhatsApp Image 2020-10-15 at 20.01.33.jpeg…]()

**Comment by J-S-Oliveira** [comment]
![WhatsApp Image 2020-10-15 at 20 01 33](https://user-images.githubusercontent.com/70406366/96740905-aa1dc800-1397-11eb-86af-37e567161650.jpeg)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96741454-2dd7b480-1398-11eb-8d9d-58cc01001e5d.png)

**Comment by J-S-Oliveira** [comment]
![CodeCogsEqn](https://user-images.githubusercontent.com/70406366/96741737-873fe380-1398-11eb-9d46-aafaa55f6ffe.gif)

**Comment by J-S-Oliveira** [comment]
![perfil](https://user-images.githubusercontent.com/70406366/96884871-62ab4080-1458-11eb-977a-b748181ac513.png)

**Comment by UnB-EngAero-170050653** [comment]
![Uploading perfil 2.png…]()

**Comment by J-S-Oliveira** [comment]
![perfil 2](https://user-images.githubusercontent.com/70406366/96884949-79ea2e00-1458-11eb-930b-517b70a2b72d.png)

**Comment by UnB-EngAero-170050653** [comment]
![Uploading 775px-Lift-force-pt.svg.png…]()

**Comment by J-S-Oliveira** [comment]
![775px-Lift-force-pt svg](https://user-images.githubusercontent.com/70406366/96885440-f715a300-1458-11eb-9152-e54a76a23338.png)

**Comment by J-S-Oliveira** [comment]
![y+](https://user-images.githubusercontent.com/70406366/96887655-2decb880-145b-11eb-9b05-8e8b6d971e6d.gif)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96925387-75d70400-148a-11eb-9cfe-80dfcc083bf3.png)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96925627-d5cdaa80-148a-11eb-94be-c1c217af1d89.png)

**Comment by J-S-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70406366/96925674-e847e400-148a-11eb-9e3d-69519fccf950.png)

**Comment by J-S-Oliveira** [comment]
![Uploading image.png…]()
