### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Jonas_Santos_170050653#2]
- Refazer as respostas dos objetivos e requisitos de solução;
- A finalidade é acadêmica ou de engenharia?
- As respostas das hipóteses de simplificação estão pobres e incompletas;
- Há muitos erros de digitação e formatação no readme;
- **Procurar escrever e descrever a modelagem com mais rigor, esta parte é muito importante!**

**Comment by lgnsparda** [comment]
- De uma forma geral, o trabalho aparenta ter sido feito de forma apressada.
- **Não é o momento para as outras etapas ainda, a modelagem está bastante fraca e incompleta!**
- **Retirar tudo que não for modelagem!**
- Evitar usar primeira pessoa no texto, trabalhos desta natureza são dissertativos.
- Tem muitos itens nos requisitos de solução. Alguns dos itens são irrealistas para o tempo colocado!
- Sua modelagem está muito fraca, o que compromete e comprometerá tudo que vier depois. Você andou tão rápido que você tirou resultados que passam a impressão de que você "pilotou" o ANSYS ao invés de fazer um trabalho de engenharia. Este programa não é um videogame! Siga as etapas conforme instruído no repositório de informações!

**Comment by J-S-Oliveira** [comment]
- De uma forma geral, o trabalho aparenta ter sido feito de forma apressada. **refazendo**
- Não é o momento para as outras etapas ainda, a modelagem está bastante fraca e incompleta! **refazendo**
- Retirar tudo que não for modelagem **Deixar a introdução do problema ou retirar as partes que se assemelham a um tutorial?**
- Evitar usar primeira pessoa no texto, trabalhos desta natureza são dissertativos. **Revisado**
- Tem muitos itens nos requisitos de solução. Alguns dos itens são irrealistas para o tempo colocado! **Quais?**
- Sua modelagem está muito fraca, o que compromete e comprometerá tudo que vier depois. Você andou tão rápido que você tirou resultados que passam a impressão de que você "pilotou" o ANSYS ao invés de fazer um trabalho de engenharia. Este programa não é um videogame! Siga as etapas conforme instruído no repositório de informações! **Refazendo**

**Comment by lgnsparda** [comment]
- Por que seu texto está todo em negrito?
- Siga o roteiro de perguntas no repositório de informações. **Você não está seguindo isto, mas sim copiando mecanicamente o vídeo da simulação!**
- Mantenha apenas o que for da parte de modelagem, porque sem isto o restante não significa muita coisa!
- Muito do que foi colocado no item de requisitos de solução não retrata o que é requisitado da simulação. Dos requisitos de solução colocados, avalia-se o seguinte:
- _valores de arrasto e de sustentação para o ângulo de ataque de 0 graus_ - Este está ok, deve melhorar a escrita.
- _Comparar os valores obtidos com os encontrados no site https://turbmodels.larc.nasa.gov/naca0012_val.html_ - A comparação dos valores obtidos são para o ângulo de 0 graus?
- _validarmos o método_ - Que método você está validando?
- _Determinar os valores de cd e cl para o ângulo de ataque de 12 graus;_ - Qual é o motivo de simular com este ângulo de ataque?
- _Comparar os valores obtidos com os encontrados no site https://turbmodels.larc.nasa.gov/naca0012_val.html;_ - Você fará isto para quantos ângulos de ataque? Dependendo de sua escolha, você precisará de bem mais do que 1 mês!
- _validarmos os resultados para o ângulo de ataque de 12 graus;_ - Novamente, qual é o motivo de simular com este ângulo de ataque?
- _realizar um estudo paramétrico da velocidade de entrada do escoamento, afim de obter os cenários de desempenho aerodinâmico do perfil.Iremos anasisar as velocidades até o limite de Ma=(0,3),pois estamos trabalhando com a hipotése de escoamento incompressível_ - **Seu estudo paramétrico não é este. Seu estudo paramétrico é da modelagem da turbulência, que eu coloquei em seu repositório e você apagou!**

**Comment by lgnsparda** [comment]
- Evitar usar primeira pessoa no texto. A escrita deve ser dissertativa aqui!
- Nos requisitos de solução, apenas o primeiro item é requisito. Os demais devem ser retirados e a escrita deve melhorar.
- Há erros de digitação no texto. Procurar ter mais rigor ao escrever!
- Usar o termo "massa específica" ao invés de "densidade". Esta terminologia é normatizada pelo INMETRO!
- Porque se escolheu uma precisão de 5%?
- CFD é a melhor opção? Esta pergunta não foi respondida!
- Tudo que não é modelagem foi retirado do repositório. Só inserir as outras partes quando a modelagem estiver pronta!

**Comment by J-S-Oliveira** [comment]
Atualizado

**Comment by lgnsparda** [comment]
- O texto do item "objetivos e finalidade" possui muitos erros de digitação e de espaçamento. **Procurar ter mais rigor ao escrever!**
- Nos itens, iniciar o texto com letra maiúscula;
- **NÃO INSERIR AS OUTRAS PARTES ENQUANTO A MODELAGEM NÃO ESTIVER PRONTA!** Tudo que não é modelagem foi retirado do repositório.

**Comment by J-S-Oliveira** [comment]
Atualizado

**Comment by lgnsparda** [comment]
- O item "Determinar se está ocorrendo o fenômeno de stall neste ângulo de ataque." nos requisitos de solução está muito ambicioso. Não seria melhor se este item fosse "Informações acerca do stall deste ângulo de ataque"?
- Os sete últimos itens do tópico "Hipóteses de Simplificações" estão deslocados. Estes itens **não são** simplificações, mas sim informações de pré-processamento.
- Porque as figuras 1 e 2 estão no item "Precisão dos Resultados"? Elas ficariam melhor em um item próprio, podendo ser intitulado "Geometria do Problema" ou na modelagem ou no pré-processamento.
- O item 1.6 precisa melhorar. Porque simulação seria melhor que experimentação em túnel de vento, por exemplo?

**Comment by J-S-Oliveira** [comment]
- O item "Determinar se está ocorrendo o fenômeno de stall neste ângulo de ataque." nos requisitos de solução está muito ambicioso. Não seria melhor se este item fosse "Informações acerca do stall deste ângulo de ataque"?**(Refeito)**
- Os sete últimos itens do tópico "Hipóteses de Simplificações" estão deslocados. Estes itens **não são** simplificações, mas sim informações de pré-processamento.**(Retirado)**
- Porque as figuras 1 e 2 estão no item "Precisão dos Resultados"? Elas ficariam melhor em um item próprio, podendo ser intitulado "Geometria do Problema" ou na modelagem ou no pré-processamento.**(Novo tópico 1.6)**
- O item 1.6 precisa melhorar. Porque simulação seria melhor que experimentação em túnel de vento, por exemplo?**(Agora é o 1.7.Refeito)**

**Comment by lgnsparda** [comment]
- Seguir para a etapa de pré-processamento
