### ISSUE TITLE
Pré-Processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Jonas_Santos_170050653#4]
- O que você quis dizer com "por sua vez é ponderado por uma malha que retrata pequenos volumes de controle"? A geração de malha é um processo de transformação de um domínio contínuo para um domínio discreto. Onde está a operação de ponderação aqui?
- Sugere-se alterar o período "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal, com um perfil traçado a partir de 200 pontos. A fim de satisfazer a precisão requerida." para "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal. O perfil é traçado a partir de 200 pontos de modo a satisfazer a precisão requerida."
- Porque o Y+ é necessário para sua simulação?
- Descrever as escolhas do pré-processamento no Fluent.

**Comment by UnB-EngAero-170050653** [comment]
- O que você quis dizer com "por sua vez é ponderado por uma malha que retrata pequenos volumes de controle"? A geração de malha é um processo de transformação de um domínio contínuo para um domínio discreto. Onde está a operação de ponderação aqui?****
- Sugere-se alterar o período "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal, com um perfil traçado a partir de 200 pontos. A fim de satisfazer a precisão requerida." para "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal. O perfil é traçado a partir de 200 pontos de modo a satisfazer a precisão requerida."**alterado**
- Porque o Y+ é necessário para sua simulação?****
- Descrever as escolhas do pré-processamento no Fluent.**coloquei as escolhas do pré-processamento em uma tabela **

**Comment by J-S-Oliveira** [comment]
- O que você quis dizer com "por sua vez é ponderado por uma malha que retrata pequenos volumes de controle"? A geração de malha é um processo de transformação de um domínio contínuo para um domínio discreto. Onde está a operação de ponderação aqui?**Refeito**
- Sugere-se alterar o período "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal, com um perfil traçado a partir de 200 pontos. A fim de satisfazer a precisão requerida." para "O domínio ao redor do aerofólio é de 20 vezes o tamanho da corda na vertical e 10 na horizontal. O perfil é traçado a partir de 200 pontos de modo a satisfazer a precisão requerida."**Alterado**
- Porque o Y+ é necessário para sua simulação?
- Descrever as escolhas do pré-processamento no Fluent.**adicionei como a imagem de uma tabela**

**Comment by lgnsparda** [comment]
- Porque o Y+ é necessário para sua simulação?
- A tabela com as escolhas do pré-processamento são insuficientes. Explicar suas escolhas como texto para complementar a tabela.

**Comment by J-S-Oliveira** [comment]
atualizado

**Comment by lgnsparda** [comment]
- Há erros de digitação na tabela de pré-processamento
- Melhorar a formatação da equação do y+

**Comment by J-S-Oliveira** [comment]
- Há erros de digitação na tabela de pré-processamento **Refeito**
- Melhorar a formatação da equação do y+ **Substituído por:** ![image](https://user-images.githubusercontent.com/70406366/100800929-07c91980-3406-11eb-9a0d-6cf6ec7a4e72.png)

**Comment by lgnsparda** [comment]
- Seguir para a etapa de Processamento e Pós-Processamento

**Comment by J-S-Oliveira** [comment]
atualizado
