### ISSUE TITLE
Processamento e Pós-Processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Jonas_Santos_170050653#5]
- As figuras 5, 6, 12 e 13 **não são** curvas de convergência!
- Há erros de digitação nesta etapa
- Fazer uma análise da física do escoamento das figuras 8, 9, 13, 14, 15 e 16
- Qual é a necessidade das figura 10 e 16 (Wall y+)?
- Porque fez-se a escolha de reiniciar a simulação com novo ângulo de ataque?
- Inserir o estudo paramétrico da modelagem da turbulência

**Comment by J-S-Oliveira** [comment]
- As figuras 5, 6, 12 e 13 **não são** curvas de convergência!   **refeito**
- Há erros de digitação nesta etapa   **revisado**
- Fazer uma análise da física do escoamento das figuras 8, 9, 13, 14, 15 e 16 **feito**
- Qual é a necessidade das figura 10 e 16 (Wall y+)?**retirado**
- Porque fez-se a escolha de reiniciar a simulação com novo ângulo de ataque?**Reformulado em 4.**
- Inserir o estudo paramétrico da modelagem da turbulência

**Comment by J-S-Oliveira** [comment]
me falaram que deveria colocar em pdf 
[github.pdf](https://github.com/Dinamica-dos-Fluidos-CFD/Jonas_Santos_170050653/files/5646003/github.pdf)

**Comment by lgnsparda** [comment]
- O que as figuras 5, 6, 12 e 13 estão mostrando? É o valor dos coeficientes ao longo das iterações?
- A análise física está muito pobre!
- O que o item "4.2 Gráficos das condições de contorno" estão descrevendo? Este título está sem sentido!

**Comment by J-S-Oliveira** [comment]
- O que as figuras 5, 6, 12 e 13 estão mostrando? É o valor dos coeficientes ao longo das iterações?**Isso,incrementado no texto**
- A análise física está muito pobre!**refeito**
- O que o item "4.2 Gráficos das condições de contorno" estão descrevendo? Este título está sem sentido!**refeito**
